language: node_js
node_js:
- '10'
services:
  - docker
before_script:
- yarn
script:
- SERVER_URL=$SERVER_URL yarn run generate
after_success:
- if [ "$TRAVIS_BRANCH" == "master" ]; then
  docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  docker build -t $DOCKER_IMAGE .;
  docker tag $DOCKER_IMAGE $DOCKER_IMAGE:$DOCKER_TAG;
  docker push $DOCKER_IMAGE;
  fi
env:
  global:
    - SERVER_URL=https://theskeleton.codenergic.org
    - DOCKER_IMAGE=codenergic/theskeleton-ui-admin
    - DOCKER_TAG=0.12.0
