language: node_js
node_js:
- '7'
before_script:
- yarn
script:
- yarn run build
before_deploy:
- openssl aes-256-cbc -K $encrypted_47773e7a01a0_key -iv $encrypted_47773e7a01a0_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -a --delete-after --quiet $TRAVIS_BUILD_DIR/dist/ build@tlsfree.org:/home/build/ui/admin/theskeleton-$TRAVIS_BUILD_ID ; ssh build@tlsfree.org 'rm -rf /home/build/ui/admin/current/*' ; ssh build@tlsfree.org 'cp -r /home/build/ui/admin/theskeleton-$TRAVIS_BUILD_ID/* /home/build/ui/admin/current/'
addons:
  ssh_known_hosts:
  - tlsfree.org
