language: node_js
node_js:
- '8'
services:
  - docker
before_script:
- yarn
script:
- SERVER_URL=$SERVER_URL yarn run generate
- docker build . --tag codenergic/theskeleton-ui-admin:latest
after_success:
- if [ "$TRAVIS_BRANCH" == "master" ]; then
  docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  docker push codenergic/theskeleton-ui-admin;
  fi
before_deploy:
- openssl aes-256-cbc -K $encrypted_47773e7a01a0_key -iv $encrypted_47773e7a01a0_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -a --delete-after --quiet $TRAVIS_BUILD_DIR/dist/ theskeleton@azure.ns.codenergic.org:/home/theskeleton/ui/admin/theskeleton-$TRAVIS_BUILD_ID ; ssh theskeleton@azure.ns.codenergic.org 'rm -rf /home/theskeleton/ui/admin/current/*' ; ssh theskeleton@azure.ns.codenergic.org 'cp -r /home/theskeleton/ui/admin/theskeleton-$TRAVIS_BUILD_ID/* /home/theskeleton/ui/admin/current/'
env:
  global:
    - SERVER_URL=https://theskeleton.codenergic.org
addons:
  ssh_known_hosts:
  - azure.ns.codenergic.org
